version: "3.9"

services:
  zigbee2mqtt:
    container_name: z2m
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/pi/.z2m/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
